name: CI Pipeline              # Workflow name (shows in GitHub UI)

on: [push, pull_request]      # When to run this workflow

jobs:                          # Define jobs
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setting up environment..."
      - run: echo "Installing dependencies..."
      - run : echo "Building..."
  
  parallel-test:
    needs: build          # Wait for build to complete
    runs-on: ubuntu-latest
    steps:
      - run: echo "running parallel task 1..."
      - run: echo "running parallel task 2..."
      - run: echo "running parallel task 3..."
  
  deploy:
    needs: [build, parallel-test]  # Wait for both build and parallel-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up deployment environment..."
      - run: echo "Deploying application"
